version: "3.7"
services:
  compilerbook:
    build:
      context: .
      args:
        TIME_ZONE: ${TIME_ZONE:-UTC}
        DEBIAN_FRONTEND: ${DEBIAN_FRONTEND:-noninteractive}
    working_dir: /home/usr/book
    volumes:
      - .:/home/usr/book
      - home:/home/user

volumes:
  home:
